-- Right side widgets (loaded right-to-left, renders left-to-right on screen)
require("items.widgets.calendar")
require("items.widgets.battery")
require("items.widgets.wifi")
require("items.widgets.volume")
require("items.widgets.music")
require("items.widgets.codexbar")
require("items.widgets.ram")
require("items.widgets.cpu")
require("items.widgets.zen")
